### ISSUE TITLE
We should use representative class names

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#122]
### Summary

The class names is-info, is-success, is-danger, ... are now used "randomly", simply to change the color of the boxes. Instead, the colors should always be in the same order, to get the intended gradient effect. Therefore it makes sense to just sort them from primary1-5

![image](https://user-images.githubusercontent.com/590385/212999981-476b24b8-3b05-40e3-9f0f-b4b32db8476b.png)

**Comment by timlinux** [comment]
The issue here is that the get translated into bulma class names during the SASS compile and changing the names wont be trivial.

**Comment by timlinux** [comment]
Another way to view this issue is that our design book colour names are not meaningful and do not convey a clear visual language in terms of what is our 'info' colour, what is our 'success' colour etc. which I think we should address, using the bulma terms.

**Comment by anitagraser** [comment]
> Another way to view this issue is that our design book colour names are not meaningful and do not convey a clear visual language in terms of what is our 'info' colour, what is our 'success' colour etc. 

Ah, but none of the five gradient colors here are meant to indicate 'info', 'success' or similar. They are just the basic default colors. 

![image](https://user-images.githubusercontent.com/590385/213516352-cbcb1547-ab50-442d-a862-ba4571235677.png)

**Comment by anitagraser** [comment]
info and success probably would be better to use the secondary colors https://www.qgis.org/de/site/getinvolved/styleguide.html
![image](https://user-images.githubusercontent.com/590385/213519802-d6dc6cfb-2e88-40a7-b47f-7115208c336d.png)

**Comment by timlinux** [comment]
Ok so I did a bit or R&D and I think we can do this:

Register the QGIS primary secondary colours as extra colours with bulma so that we can use e.g. class="is-qgis-primary1" as modifiers (e.g. when we want to use the green gradient colours for boxes) and then assign meaningful colours to the Bulma roles of info, success, warning etc. 

That way when we have a semantic use of colour (e.g. to show the user something they should be alerted to) we have a suitable palette, and when we want our QGIS primary and secondary colours we have those too. I will make a first pass implementation and then you can shuffle the colours around as you like as per your current PR #121

**Comment by timlinux** [comment]
See also https://stackoverflow.com/questions/68418119/how-to-add-custom-colors-to-bulma

**Comment by timlinux** [comment]
I'm going to close this now -  I think we just need to stick with the system we have in place.
