### ISSUE TITLE
Please shrink down the homepage content elements on desktop displays, it takes 17 scrolls to reach the bottom.

### ISSUE THREAD

**Issue by ProfessorDey** [qgis/QGIS-Website#148]
### Feature Description

I've found a trend where newer websites make more and more full page powerpoint style website designs that look great on mobile but are a slog to get anything useful out of on a regular 16:9 desktop. The biggest issue is the item scaling not making sense for a horizontal display. This results in huge bloated sections of not much of value and having to hunt around the screen to find the actual text and content.

If the desktop version could be shrunk down or preferably split into a double column, that'd go a long way towards improving legibility for general users, who will be the main ones using the website, since the only reason to open it on mobile is to promote the project to others.

As it is I can barely see one 'page' of information and am barely getting a couple snippets of information out of it, so it just becomes a lot of visual noise. I'm actively having to turn my head to read anything on my 28" display.
![image](https://github.com/qgis/QGIS-Hugo/assets/32119091/562406db-2787-4ca2-b4a9-fb24c2f625b9)
![image](https://github.com/qgis/QGIS-Hugo/assets/32119091/cb123d4f-c2d5-425d-b7a8-8d31e3fdc36b)

**Comment by timlinux** [comment]
Hi @ProfessorDey I really appreciate you taking time to make this ticket. I think we need to realise that we are not going to build something that is universally accepted as 'perfect' since people have such different tastes and preferences. At this point I will close this issue since I don't think we have the resources/time/energy to reimplement the site with a new visual paradigm. If you are a web developer and interested in pursuing this, I will be happy to review suggestions which a) provide a new design as wireframe and b) and roadmap for implementing the design.
