### ISSUE TITLE
The latest website build is 1 week old or the commit revision in the footer is not up-to-date

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Website#381]
### URL

https://www.qgis.org/

### Summary

https://github.com/qgis/QGIS-Website/commit/94b9a1fe Jul 23, 2024.

![image](https://github.com/user-attachments/assets/a2191667-4491-4ce8-8c9c-373308330eba)

**Comment by jef-n** [comment]
because https://github.com/qgis/QGIS-Website/actions/workflows/deploy-prod.yml is disabled?

**Comment by Xpirix** [comment]
Thanks for reporting @agiudiceandrea, please find the proposed fix for this at #382.

> because https://github.com/qgis/QGIS-Website/actions/workflows/deploy-prod.yml is disabled?

Yes, that's right. The deployment is not automatic yet. For now, we've made some commands in the Makefile that should facilitate it.

**Comment by agiudiceandrea** [comment]
Thanks @Xpirix. Is the QGIS website actually more then 1 week old or the issue is only with the commit revision in the footer which is not up-to-date?
Anyway it seems to me the QGIS website is currently at least some days old.

**Comment by Xpirix** [comment]
@agiudiceandrea, I agree, the latest deployment was done some days ago. The QGIS website is currently running on this commit revision: https://github.com/qgis/QGIS-Website/tree/6aadd631c4862f85527d81b345505a9be976544b. We will deploy the latest changes soon along with the fix for the commit revision in the footer.
(Cc @timlinux )

**Comment by timlinux** [comment]
Yes just to echo @Xpirix , we are currently deploying manually for the first few months and then we will add automatic deployments.
