### ISSUE TITLE
Remove unused files 

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#445]
While looking for a way to update the news bar at the top of the home page, I stumbled upon some seemingly unused files. As far as I can tell, these files are not used:

- https://github.com/qgis/QGIS-Website/blob/fd58eaf50d255f7d34412f0fb508f7a107a378b4/source/feeds/qugsnews.atom
- https://github.com/qgis/QGIS-Website/blob/fd58eaf50d255f7d34412f0fb508f7a107a378b4/content/news/amy.md

**Comment by Xpirix** [comment]
@anitagraser Cc @timlinux 

I think the file `qugsnews.atom` is still used by the `fetch_feed.py`. However, I wonder if we still need to fetch the User Group Feed from this file.
https://github.com/qgis/QGIS-Website/blob/5059b3dde45b5cafdc562d40077493cffc3c8cf5/fetch_feeds.py#L232

About the news bar, I think it fetches the data from feed.qgis.org. But it seems that it didn't get the latest update because the User Conference entry is not listed there anymore. I will try to see further how it works.

https://github.com/qgis/QGIS-Website/blob/5059b3dde45b5cafdc562d40077493cffc3c8cf5/themes/hugo-bulma-blocks-theme/layouts/partials/contextmenu.html#L5

https://github.com/qgis/QGIS-Website/blob/5059b3dde45b5cafdc562d40077493cffc3c8cf5/config.toml#L96

**Comment by Xpirix** [comment]
@timlinux I think adding a new task to the `fetch_feeds.py` is better to keep synchronisation from the feed website because the content of the news bar is only updated once and doesn't seem to update even if we rebuild the static deployment files. What do you think?
